trigger:
  branches:
    include:
      - main
      - ado
  paths:
    exclude:
      - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-24.04'

steps:
- script: |
    echo "Hello World"
  displayName: 'Print Hello World'
